### ISSUE TITLE
[Blocked until requirements from stakeholders is formed] What text should appear in error message/notification if validation wasn't successfull?

### ISSUE THREAD

**Issue by kikimou** [ita-social-projects/ZeroWaste#436]
Paragraph 10 in US #428

**Comment by kikimou** [comment]
Answer: the exact text in the site, but in Acceptance Criteria should be a number of error

**Comment by kikimou** [comment]
Need to write:

1. Errors for "Site Name" field - can't write errors because there are no length or formatting requirements.
2. Errors for "Favicon" - can't write errors because there are no required format and size specifications.

**Comment by onakone** [comment]
Errors for the "Site Name" field - can't write errors because there are no length or formatting requirements.
 
length should be  from 3 to 30
regarding  formatting there are any specifications, you can modify this part of an AC

Errors for "Favicon" - can't write errors because there are no required format and size specifications.

Favicon must be a multiple of 48px square, for example: 48x48px, 96x96px, 144x144px and so on. 
SVG files don't have a specific size. Any valid favicon format is supported. 
The favicon URL must be stable (don't change the URL frequently).
