### ISSUE TITLE
On the page site settings is duplicating text simultaneously in text fields.

### ISSUE THREAD

**Issue by Andriyua7** [ita-social-projects/ZeroWaste#470]
Precondition: Valid Login and Password

Steps to Reproduce:

1. Log in to the site like admin user.
2. Go to [Site Settings](https://zero-waste-staging.onrender.com/en/account/site_setting/edit)
3. Enter text into the text field of Title.

Expected Result:
Text is entered.

Actual Result:
The drawing container is displayed vhile there is no image.

**Comment by dafeys** [comment]
The text entered in the Title field is displayed correctly. Previews with a Title and Favicon are also displayed correctly. 
Displaying an empty container for favicon is caused by [#532](https://github.com/orgs/ita-social-projects/projects/25?pane=issue&itemId=34253589) issue (Favicon lasts for ~20 min after uploading, then dissapears )



![Image](https://github.com/ita-social-projects/ZeroWaste/assets/36037839/84684795-f0c1-49f0-a57b-1f4317715183)
